keys:
  - &admin_pmallapp age1547vqtqhgtxu54eewxwttjsfd85w0lm4f46fyxxhnx2ydxt7kyxs36ts2d
  - &user_premunix_pmallapp age13xfa77f49ne56z3yyqh9qc9upjmrjfva8kcvg3jfem2m99dhr9fs34gdrp
  - &user_CORE_nixos age1qh2epukpmcg69386v5shr3w9l2tvryan4xr8npdk8tkth62jtpwqg4u0n3
  - &user_khanelimac_pmallapp age1q2qaahrx4chvsa5g7xqwrwk28mld6kn4md8crcrqg046m8yt2efsugl8vr
  - &admin_khanelimac_pmallapp age1xxpd2a56xjj9kzx7xt2ax6w36a68vtzcd8enrnvup6m6wfr6upwq8fr5h5
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
  - path_regex: secrets/CORE/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *admin_khanelimac_pmallapp
          - *user_premunix_pmallapp
          - *user_khanelimac_pmallapp
  - path_regex: secrets/CORE/nixos/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *user_CORE_nixos
  - path_regex: secrets/nuc-v09/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
  - path_regex: secrets/khanelimac/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *admin_khanelimac_pmallapp
          - *user_khanelimac_pmallapp
  - path_regex: secrets/khanelimac/pmallapp/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *admin_khanelimac_pmallapp
          - *user_khanelimac_pmallapp
  - path_regex: secrets/premunix/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *user_premunix_pmallapp
  - path_regex: secrets/premunix/pmallapp/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *user_premunix_pmallapp
  - path_regex: secrets/pmallapp/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_pmallapp
          - *admin_khanelimac_pmallapp
          - *user_premunix_pmallapp
          - *user_CORE_nixos
          - *user_khanelimac_pmallapp
